sudo: false

language:
  - cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6 

script:
  - mkdir -p build
  - cd build
  - CXX=/usr/bin/g++-6 cmake ..
  - make
  - ./test/test_zad


notifications:
email: false
